version: "3.3"

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  celery-worker:
    build: .
    command: celery -A TeamStatGoogleApi worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A TeamStatGoogleApi beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis

  flower:
    image: mher/flower
    command: celery flower -A TeamStatGoogleApi
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - redis
