version: "3.3"

services:
  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - '6379:6379'

  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  celery-worker:
    container_name: worker
    build: .
    command: celery -A TeamStatGoogleApi worker -B -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - web

  celery-beat:
    container_name: beat
    build: .
    command: celery -A TeamStatGoogleApi beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - celery-worker
