version: "3.3"

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  celery-worker:
    build: .
    command: celery -A TeamStatGoogleApi worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - web